apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ewd-assignment1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ewd-assignment1
    app.kubernetes.io/part-of: ewd-assignment1
  name: ewd-assignment1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: ewd-assignment1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: ewd-assignment1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/catoconn-rhmi-tenant/ewd-assignment1/ewd-assignment1@sha256:ea9551e25c84640841a9316efb93e7d58111e496cd3e246d6f84a9b6e826f1e4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
