apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ewd-assignment1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/catoconn-rhmi-tenant/ewd-assignment1/ewd-assignment1@sha256:ea9551e25c84640841a9316efb93e7d58111e496cd3e246d6f84a9b6e826f1e4
        name: my-nodejs
        resources: {}
status: {}
